#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcEQM, 2014-09-10 12:46:00 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. EQM
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpRdcEQM as RdcEQM

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("EventNumber","3990")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
#DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc Service
#DMPSW.RootIOSvc.Set("InData/Update","DmpRdcData.root")        # save output into input root file, if you really need
DMPSW.RootIOSvc.Set("OutData/WriteList","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = RdcEQM.DmpAlgRdcEQM()
#rdcAlgBT.Set("Psd/Connector","Psd/EQM")
#rdcAlgBT.Set("Stk/Connector",Stk/EQM")
rdcAlgBT.Set("Bgo/Connector","Bgo/EQM")
#rdcAlgBT.Set("Nud/Connector","Nud/EQM")
rdcAlgBT.Set("BinaryFile","/Users/danny/software/dmpwork/DataSample/A2Data00_20140513-155749.frd")
DMPSW.RootIOSvc.Set("OutData/FileName","./test/DmpRdcData1.root")        # if NOT set, will use input name
#rdcAlgBT.Set("BinaryFile","test_A2Data00_20140513-191731.frd")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


