#! /usr/bin/python
'''
 *  $Id: JobOpt_DmpRdcEQM, 2014-08-12 18:41:47 DAMPE $
 *  Author(s):
 *    Chi WANG (chiwang@mail.ustc.edu.cn) 11/03/2014
 *-----------------------------------------------------
 *      Example of how to run Rdc of DAMPE. EQM
 *-----------------------------------------------------
'''

#-------------------------------------------------------------------
import DMPSW                    # Load DAMPE software
import libDmpRdcEQM as DmpRdcAlg

#-------------------------------------------------------------------
# Global setting
#DMPSW.Core.Set("EventNumber","100")     # If NOT set, will use 1234567890
#DMPSW.Core.Set("StartTime","20130101-0000")     # if NOT set, start from launch time
#DMPSW.Core.Set("StopTime","20160101-0000")      # if NOT set, end at 2113.01.01
DMPSW.Core.Set("LogLevel","Debug")      # Value = {Error | Warning | Info | Debug}. If NOT set, will use Info.

#-------------------------------------------------------------------
# RootIOSvc Service
#DMPSW.RootIOSvc.Set("InData/Update","DmpRdcData.root")        # save output into input root file, if you really need
DMPSW.RootIOSvc.Set("OutData/FileName","./test/DmpRdcData.root")        # must set it, if NOT set, will not save anything
DMPSW.RootIOSvc.Set("OutData/WriteList","Event/Rdc/EventHeader;Event/Rdc/Bgo")  # split by ;

#-------------------------------------------------------------------
# Creat user's service or algorithm
rdcAlgBT = DmpRdcAlg.DmpRdcAlgEQM()
rdcAlgBT.Set("PackageNumber","30")
#rdcAlgBT.Set("Psd/Connector","Psd/EQM")
#rdcAlgBT.Set("Stk/Connector",Stk/EQM")
rdcAlgBT.Set("Bgo/Connector","Bgo/EQM")
#rdcAlgBT.Set("Nud/Connector","Nud/EQM")
rdcAlgBT.Set("BinaryFile","A2Data00_20140501-190145.frd")

#-------------------------------------------------------------------
# Append user's service or algorithm into Kernel
DMPSW.AlgMgr.Append(rdcAlgBT)

#-------------------------------------------------------------------
# Run job
DMPSW.Core.Initialize()
DMPSW.Core.Run()
DMPSW.Core.Finalize()


